/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFountainsdbRouteImport } from './routes/api/fountainsdb'
import { Route as ApiEspRouteImport } from './routes/api/esp'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFountainsdbRoute = ApiFountainsdbRouteImport.update({
  id: '/api/fountainsdb',
  path: '/api/fountainsdb',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEspRoute = ApiEspRouteImport.update({
  id: '/api/esp',
  path: '/api/esp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/esp': typeof ApiEspRoute
  '/api/fountainsdb': typeof ApiFountainsdbRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/esp': typeof ApiEspRoute
  '/api/fountainsdb': typeof ApiFountainsdbRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/esp': typeof ApiEspRoute
  '/api/fountainsdb': typeof ApiFountainsdbRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/api/esp' | '/api/fountainsdb'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/api/esp' | '/api/fountainsdb'
  id: '__root__' | '/' | '/dashboard' | '/api/esp' | '/api/fountainsdb'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ApiEspRoute: typeof ApiEspRoute
  ApiFountainsdbRoute: typeof ApiFountainsdbRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fountainsdb': {
      id: '/api/fountainsdb'
      path: '/api/fountainsdb'
      fullPath: '/api/fountainsdb'
      preLoaderRoute: typeof ApiFountainsdbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/esp': {
      id: '/api/esp'
      path: '/api/esp'
      fullPath: '/api/esp'
      preLoaderRoute: typeof ApiEspRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ApiEspRoute: ApiEspRoute,
  ApiFountainsdbRoute: ApiFountainsdbRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
